### ISSUE TITLE
Teach Royce how to use

### ISSUE THREAD

**Issue by r-havelka** [anthonymorast/AllyInvest.py#3]
**I'm submitting a ... (check one with "x")**

````
[x] bug report
[ ] feature request
[ ] support request
````

**Current behavior**

I am unable to play with Anthony's Investment toy. I haven't tried yet but it looks hard.

**Expected behavior**

I'm not sure yet. I haven't played with Anthony's toy

**Minimal reproduction of the problem with instructions**

Do nothing, that's literally all I've done

**What is the motivation / use case for changing the behavior?**

I want to play with Anthony's toy

**Please tell us about your environment:**

It isn't set up

**Comment by anthonymorast** [comment]
I've experienced this as well.

When I first started the project and didn't have any code written I wasn't able to use the API either. You just need an Ally account to get your keys, then copy the Ally folder from the repo to wherever your Python script is. Then you can make function calls.

Here's a list of function calls: [http://www.anthonymorast.com/allyinvestapi/classally_1_1_ally_a_p_i.html](http://www.anthonymorast.com/allyinvestapi/classally_1_1_ally_a_p_i.html)
